dist: xenial
language: python
python: 3.7

addons:
  apt:
    sources:
    - deadsnakes
    packages:
    - python3.4
    - python3.5
    - python3.6

install:
- pip install tox
- pip install coveralls

script:
- tox

after_success:
- coveralls
