dist: xenial
language: python
python: 3.9

addons:
  apt:
    sources:
    - deadsnakes
    packages:
    - python3.6
    - python3.7
    - python3.8

install:
- pip install tox
- pip install coveralls

script:
- tox

after_success:
- coveralls
